In [8]:
import numpy as np 


# Question 1

In [14]:
arr = np.array([[24],[2],[-3],[-23]])

In [15]:
arr

array([[ 24],
       [  2],
       [ -3],
       [-23]])

In [16]:
arT = arr.T

In [17]:
arT

array([[ 24,   2,  -3, -23]])

In [28]:
# Pytorch
import torch
x = torch.tensor([[24],[2],[-3],[-23]])
x


tensor([[ 24],
        [  2],
        [ -3],
        [-23]])

In [29]:
xT = x.T
xT

tensor([[ 24,   2,  -3, -23]])

# Question 2

In [19]:
y = np.array([[42,4,7,99],[-99,-3,17,22]])

In [20]:
y

array([[ 42,   4,   7,  99],
       [-99,  -3,  17,  22]])

In [21]:
y.shape

(2, 4)

In [30]:
#pytorch
y = torch.tensor([[42,4,7,99],[-99,-3,17,22]])
y

tensor([[ 42,   4,   7,  99],
        [-99,  -3,  17,  22]])

In [31]:
y.shape

torch.Size([2, 4])

# Question 3

In [25]:
print(y[[1],[2]])

[17]


In [33]:
y[[1],[2]]

tensor([17])