# Question 1


In [1]:
import numpy as np

In [2]:
y = np.array([[42,4,7,99],[-99,-3,17,22]])


In [3]:
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

# Question 2 Hadamard product of matrices

In [4]:
import torch

In [5]:
x = torch.tensor([[25,10],[-2,1]])
y = torch.tensor([[-1,7],[10,8]])


In [6]:
print(x * y)

tensor([[-25,  70],
        [-20,   8]])


# Question 3

### dot product of tensors w and x

In [7]:
w = torch.tensor([-1,2,-2])
x = torch.tensor([5,10,0])

In [8]:
DotProduct = torch.dot(w,x)
print(DotProduct)

tensor(15)


In [9]:
import tensorflow as tf
tf.reduce_sum(tf.multiply(w,x)) 

<tf.Tensor: shape=(), dtype=int64, numpy=15>

In [10]:
a = torch.tensor([[0,1,2],[3,4,5,],[6,7,8]])
b = torch.tensor([[-1,0],[1,1],[2,2]])


In [11]:
torch.matmul(a,b)

tensor([[ 5,  5],
        [11, 14],
        [17, 23]])

# EXERCISE 4

In [15]:
matrix_1 = np.array([[1,0,0], [0,1,0], [0,0,1]])
matrix_1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [16]:
# take out the columns into individual matrix.
v1 = matrix_1[:, 0]
v2 = matrix_1[:, 1]
v3 = matrix_1[:, 2]

In [17]:
print(v1)
print(v2)
print(v3)

[1 0 0]
[0 1 0]
[0 0 1]


In [18]:
# if dot product of any 2 vector is 0, then 2 vectors are orthogonal to each other.
print(np.dot(v1, v2))
print(np.dot(v1, v3))
print(np.dot(v2, v3))


0
0
0


In [19]:
# if the norm is 1 then it is unit norm.
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.linalg.norm(v3))


1.0
1.0
1.0


# now with second matrix

In [21]:

matrix_2 = np.array([[2/3, -2/3, 1/3], [1/3, 2/3, 2/3], [2/3, 1/3, -2/3]])

# take out the columns into individual matrix.


In [22]:
v1 = matrix_2[:, 0]
v2 = matrix_2[:, 1]
v3 = matrix_2[:, 2]


In [23]:
print(v1)
print(v2)
print(v3)

[0.66666667 0.33333333 0.66666667]
[-0.66666667  0.66666667  0.33333333]
[ 0.33333333  0.66666667 -0.66666667]


## if dot product of any 2 vector is 0, then 2 vectors are orthogonal to each other.


In [24]:
print(np.dot(v1, v2))
print(np.dot(v1, v3))
print(np.dot(v2, v3))

0.0
0.0
0.0


## if the norm is 1 then it is unit norm

In [25]:
print(np.linalg.norm(v1))
print(np.linalg.norm(v2))
print(np.linalg.norm(v3))

1.0
1.0
1.0
