# Question 1


In [17]:
import numpy as np

In [18]:
y = np.array([[42,4,7,99],[-99,-3,17,22]])


In [19]:
y.T

array([[ 42, -99],
       [  4,  -3],
       [  7,  17],
       [ 99,  22]])

# Question 2 Hadamard product of matrices

In [20]:
import torch

In [21]:
x = torch.tensor([[25,10],[-2,1]])
y = torch.tensor([[-1,7],[10,8]])


In [22]:
print(x * y)

tensor([[-25,  70],
        [-20,   8]])


# Question 3

### dot product of tensors w and x

In [23]:
w = torch.tensor([-1,2,-2])
x = torch.tensor([5,10,0])

In [24]:
DotProduct = torch.dot(w,x)
print(DotProduct)

tensor(15)


In [25]:
import tensorflow as tf
tf.reduce_sum(tf.multiply(w,x)) 

<tf.Tensor: shape=(), dtype=int64, numpy=15>