In [14]:
import numpy as np
import torch

In [6]:

X = np.array([[4, 2], [-5, -3]])
X

array([[ 4,  2],
       [-5, -3]])

In [8]:
np.linalg.det(X)
# also the array must be square to calculate the determinant

-2.0000000000000013

In [9]:
N = np.array([[-4, 1], [-8, 2]])
N

array([[-4,  1],
       [-8,  2]])

In [10]:

np.linalg.det(N)

0.0

In [12]:
# Ninv = np.linalg.inv(N)
# we cannot calculate the inverse of a matrix with a determinant of 0

In [15]:
N = torch.tensor([[-4, 1], [-8, 2.]]) # must use float not int


In [16]:
torch.det(N)

tensor(-0.)

## Generalizing Determinants

In [17]:
X = np.array([[1, 2, 4], [2, -1, 3], [0, 5, 1]])
X

array([[ 1,  2,  4],
       [ 2, -1,  3],
       [ 0,  5,  1]])

In [18]:

np.linalg.det(X)

19.999999999999996