In [2]:
import torch

In [9]:
# X is the input tensor
X = torch.tensor([[4,2],[-5,-3]],dtype=torch.float32)
X


tensor([[ 4.,  2.],
        [-5., -3.]])

In [13]:
# y is the output
y = torch.tensor([4,-7],dtype=torch.float32)
y

tensor([ 4., -7.])

### Xw = y

### X<sup>-1</sup> Xw = y

In [14]:
X1 = torch.inverse(X)
X1

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]])

### let's find w weight

In [16]:
w = torch.matmul(X1,y)
w

tensor([-1.,  4.])

### since Xw = y

In [18]:
print(y == torch.matmul(X,w))

tensor([True, True])
