# The Moore-Penrose Psudeoinverse

Let's calculate the pseudoinverse $A^+$ of some matrix $A$ using the formula from the slides: 

$A^+ = VD^+U^T$

In [1]:
import torch

In [4]:
A = torch.tensor([[-1,2],[3,-2],[5,7]],dtype=torch.float32)
A

tensor([[-1.,  2.],
        [ 3., -2.],
        [ 5.,  7.]])

In [5]:
U, d , VT = torch.linalg.svd(A)

In [6]:
U

tensor([[ 0.1271,  0.4741,  0.8713],
        [ 0.0016, -0.8785,  0.4778],
        [ 0.9919, -0.0593, -0.1124]])

In [8]:
# now to create D+, we first invert the diagonal matrix D
D = torch.diag(d)

In [13]:
D_inv = torch.inverse(D)
D_inv

tensor([[0.1154, 0.0000],
        [0.0000, 0.2436]])

In [24]:
Dplus = torch.concatenate((D_inv, torch.tensor([[0, 0]]).T), axis=1)
Dplus


tensor([[0.1154, 0.0000, 0.0000],
        [0.0000, 0.2436, 0.0000]])

In [25]:
torch.matmul(VT.T, torch.matmul(Dplus, U.T))

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])

In [26]:
torch.linalg.pinv(A)

tensor([[-0.0877,  0.1777,  0.0758],
        [ 0.0766, -0.1193,  0.0869]])