In [1]:
import numpy as np

As on slides, SVD of matrix $A$ is: 

$A = UDV^T$

Where: 

* $U$ is an orthogonal $m \times m$ matrix; its columns are the **left-singular vectors** of $A$.
* $V$ is an orthogonal $n \times n$ matrix; its columns are the **right-singular vectors** of $A$.
* $D$ is a diagonal $m \times n$ matrix; elements along its diagonal are the **singular values** of $A$.

In [2]:
A = np.array([[-1, 2], [3, -2], [5, 7]])
A

array([[-1,  2],
       [ 3, -2],
       [ 5,  7]])

In [3]:
U, d, VT = np.linalg.svd(A)

In [4]:
U # left singular vectors

array([[ 0.12708324,  0.47409506,  0.87125411],
       [ 0.00164602, -0.87847553,  0.47778451],
       [ 0.99189069, -0.0592843 , -0.11241989]])

In [7]:
d # diagonal vectors of singular values

array([8.66918448, 4.10429538])

$D$ must have the same dimensions as $A$ for $UDV^T$ matrix multiplication to be possible: 

In [18]:
D = np.concatenate((np.diag(d), [[0, 0]]), axis=0)
D

array([[8.66918448, 0.        ],
       [0.        , 4.10429538],
       [0.        , 0.        ]])

In [6]:
VT

array([[ 0.55798885,  0.82984845],
       [-0.82984845,  0.55798885]])

In [19]:
np.dot(U, np.dot(D, VT))

array([[-1.,  2.],
       [ 3., -2.],
       [ 5.,  7.]])

SVD and eigendecomposition are closely related to each other: 

* Left-singular vectors of $A$ = eigenvectors of $AA^T$.
* Right-singular vectors of $A$ = eigenvectors of $A^TA$.
* Non-zero singular values of $A$ = square roots of eigenvalues of $AA^T$ = square roots of eigenvalues of $A^TA$


In [20]:
import torch

In [21]:
B = torch.tensor([[25,2,-5],[3,-2,1],[5,7,4.]])
B

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [23]:
Ub , db, VTb = torch.linalg.svd(B)

* Left-singular vectors of $A$ = eigenvectors of $AA^T$.


In [24]:
Ub

tensor([[-0.9757, -0.1823, -0.1214],
        [-0.0975, -0.1350,  0.9860],
        [-0.1961,  0.9739,  0.1140]])

In [37]:
AAT = torch.matmul(B, B.T)
AAT

tensor([[654.,  66., 119.],
        [ 66.,  14.,   5.],
        [119.,   5.,  90.]])

In [33]:
lambdas,EV = torch.linalg.eig(AAT)
EV

tensor([[ 0.9757+0.j,  0.1823+0.j,  0.1214+0.j],
        [ 0.0975+0.j,  0.1350+0.j, -0.9860+0.j],
        [ 0.1961+0.j, -0.9739+0.j, -0.1140+0.j]])

* Right-singular vectors of $A$ = eigenvectors of $A^TA$.


In [35]:
VTb

tensor([[-0.9810, -0.1196,  0.1528],
        [-0.0113,  0.8211,  0.5706],
        [ 0.1937, -0.5581,  0.8069]])

In [38]:
ATA = torch.matmul(B.T, B)


In [39]:
lambdas2,EV2 = torch.linalg.eig(ATA)
EV2

tensor([[ 0.9810+0.j,  0.1937+0.j, -0.0113+0.j],
        [ 0.1196+0.j, -0.5581+0.j,  0.8211+0.j],
        [-0.1528+0.j,  0.8069+0.j,  0.5706+0.j]])