In [2]:
import torch

The **eigendecomposition** of some matrix $A$ is 

$A = V \Lambda V^{-1}$

Where: 

* As in examples above, $V$ is the concatenation of all the eigenvectors of $A$
* $\Lambda$ (upper-case $\lambda$) is the diagonal matrix diag($\lambda$). Note that the convention is to arrange the lambda values in descending order; as a result, the first eigenvalue (and its associated eigenvector) may be a primary characteristic of the matrix $A$.

In [14]:
B = torch.tensor([[25,2,-5],[3,-2,1],[5,7,4.]])
B

tensor([[25.,  2., -5.],
        [ 3., -2.,  1.],
        [ 5.,  7.,  4.]])

In [21]:
lambdas, V = torch.linalg.eig(B)

In [22]:
lambdas

tensor([23.7644+0.j,  6.6684+0.j, -3.4328+0.j])

In [23]:
lambdasD = torch.diag(lambdas)  
lambdasD

tensor([[23.7644+0.j,  0.0000+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  6.6684+0.j,  0.0000+0.j],
        [ 0.0000+0.j,  0.0000+0.j, -3.4328+0.j]])

In [17]:
V

tensor([[ 0.9511+0.j, -0.2386+0.j,  0.1626+0.j],
        [ 0.1218+0.j, -0.1924+0.j, -0.7705+0.j],
        [ 0.2837+0.j, -0.9519+0.j,  0.6163+0.j]])

In [18]:
# inverse
V_inv = torch.linalg.inv(V)
V_inv

tensor([[ 1.1356+0.j,  0.0102+0.j, -0.2868+0.j],
        [ 0.3914-0.j, -0.7198-0.j, -1.0032-0.j],
        [ 0.0817-0.j, -1.1164-0.j,  0.2052-0.j]])

Confirm that $A = V \Lambda V^{-1}$: 

In [28]:
A = V @ lambdasD @ V_inv
A

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])

In [30]:
A = torch.linalg.matmul(V,torch.linalg.matmul(lambdasD,V_inv))
A

tensor([[25.0000+0.j,  2.0000+0.j, -5.0000+0.j],
        [ 3.0000+0.j, -2.0000+0.j,  1.0000+0.j],
        [ 5.0000+0.j,  7.0000+0.j,  4.0000+0.j]])

Eigendecomposition is not possible with all matrices. And in some cases where it is possible, the eigendecomposition involves complex numbers instead of straightforward real numbers. 

In machine learning, however, we are typically working with real symmetric matrices, which can be conveniently and efficiently decomposed into real-only eigenvectors and real-only eigenvalues. If $A$ is a real symmetric matrix then...

$A = Q \Lambda Q^T$

...where $Q$ is analogous to $V$ from the previous equation except that it's special because it's an orthogonal matrix. 

In [32]:
import numpy as np
A = np.array([[2, 1], [1, 2]])
A

array([[2, 1],
       [1, 2]])

In [33]:
lambdas, Q = np.linalg.eig(A)

In [34]:
Lambda = np.diag(lambdas)
Lambda

array([[3., 0.],
       [0., 1.]])

In [35]:
Q

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])



```
# This is formatted as code
```

Let's confirm $A = Q \Lambda Q^T$: 

In [36]:
np.dot(Q, np.dot(Lambda, Q.T))

array([[2., 1.],
       [1., 2.]])

(As a quick aside, we can demostrate that $Q$ is an orthogonal matrix because $Q^TQ = QQ^T = I$.)

In [37]:
np.dot(Q.T, Q)

array([[1., 0.],
       [0., 1.]])

In [38]:
np.dot(Q, Q.T)

array([[1., 0.],
       [0., 1.]])