In [5]:
# Vector (Rank 1 Tensors) in Numpy
import numpy as np

In [6]:
x = np.array([25,2,5])
x

array([25,  2,  5])

In [7]:
len(x)

3

In [8]:
x.shape

(3,)

In [9]:
type(x)

numpy.ndarray

In [10]:
#Vector Transposition

In [11]:
# Transposing a regular 1D array has no effect 
x_t = x.T
x_t

array([25,  2,  5])

In [12]:
y = np.array([[25,2,5]])
y

array([[25,  2,  5]])

In [13]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [14]:
y_t.shape

(3, 1)

In [15]:
# Vectors in PyTorch and TensorFlow

In [16]:
import torch
x_pt = torch.tensor([25,5,6])
x_pt

ModuleNotFoundError: No module named 'torch'

### $L^2$ Norm

In [2]:
np.linalg.norm(x)

NameError: name 'np' is not defined

# $L^1$ Norm

In [ ]:
np.abs(25) + np.abs(5) + np.abs(6)

## squared $L^2$ Norm

In [3]:
np.dot(x,x)

NameError: name 'np' is not defined

## orthogonal Vectors

In [4]:
i = np.array([1,0,0])
j = np.array([0,1,0])

np.dot(i,j)

NameError: name 'np' is not defined

# Matrices (Rank 2 Tensors ) in numpy

In [17]:
X = np.array([[1,2,3],[4,5,6],[7,8,9]])
X

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
X.shape

(3, 3)

In [19]:
X.size

9

In [20]:
X[:,0]

array([1, 4, 7])

# Higher Rank Tensors
As an example, rank 4 tensors are common for images, where each dimension corresponds to:

1. Number of images in training batch, e.g., 32
2. Image height in pixels, e.g., 28 for [MNIST digits](http://yann.lecun.com/exdb/mnist/)
3. Image width in pixels, e.g., 28
4. Number of color channels, e.g., 3 for full-color images (RGB)